<a href="https://colab.research.google.com/github/pravinbaste009/Deep-Learining/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this section we are going to learn about tensors with the help of tentensorflow 

More Specifically, We will see the
* introduction to tensors
* Getting information from tensors
* Manipualting tensors
* Tensors and Numpy
* Using @tf.funtion
* Using GPUs with TensorFLOW
* Excersice for practice

## Introduction to Tesnors

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# creating tensors wtih tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of tensro ( ndim stands for number of diamensions)
scaler.ndim

0

In [ ]:
# create a vector
vector =tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check dimensions of vector
vector.ndim

1

In [ ]:
# create a matrix ( has more than q dimensions)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# check dimensions of matrix
matrix.ndim

2

In [ ]:
# create another matrix
another_matrix = tf.constant([[10. ,7.],
                              [3. ,2.],
                              [8. , 9.]], dtype=tf.float16) # spefify the datatype of constant
another_matrix                              


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Lets make summary what we learned till now.
* Scaler : a single number
* vector : number with directions
* Matrix: 2-dimentional array of numbers
* tensor : n-dimentional array (0-dimentional array is scalar and 1-diamentional array is vector )

 ## Creating tensors with tf.variable

In [ ]:
# Create the same name with tf.variable() as above
changeable_tensor =tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try to change the values of changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### creating random tensors

In [ ]:
# create two random ( but the same)  tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal (shape=(3,2))
random_2 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_2 = random_2.normal (shape=(3,2))

In [ ]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

In [ ]:
# letsc check both are same or not
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

### Shuffle ther order of elements tin a tensor

In [ ]:
# not shuffled tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# lets make it suffle
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# lets make it suffle (again run, we will get it different order everytime)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42) 
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42) 
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=43) 
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled,seed=42) 
     

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(2) # Global Seed
tf.random.shuffle(not_shuffled,seed=42) # internal Seed 
  

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

## Other ways to create tensor

In [ ]:
# create tensor of all ones
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NUmoy arrys into tensors
The main differance between NumPy and tensorflow tensors is that tensors can be run on GPU ( much faster computing ).

In [ ]:
# create numpy array between 1 to 25
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)


In [ ]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# try to convert numpy array into tensor
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
# Now we will try change shape 2x3x4=24
A=tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
# Now we will try change shape 8X4=24
B=tf.constant(numpy_A, shape=(8,3))
B

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

## Getting more information from Tensor
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
 # create a rank 4 tensor 
 rank_4_tensor= tf.zeros(shape=[2,3,4,5])
 rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
# get various attribute of our tensor
print('Datatype of every element: ',rank_4_tensor.dtype)
print('Number of dimensions (rank): ',rank_4_tensor.ndim)
print('Shape of tensor: ',rank_4_tensor.shape)
print('Elements along the 0 axis: ',rank_4_tensor.shape[0])
print('Elements along the last axis: ',rank_4_tensor.shape[-1])
print('Number of Elements in tensor: ',tf.size(rank_4_tensor))
print('Number of Elements in tensor: ',tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Number of Elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)
Number of Elements in tensor:  120


# Indexing tensors
Tensors can be indexed just like Python Lists.



In [ ]:
# Get the firsr 2 elements of rach dimensions.
rank_4_tensor[:2,:2,:2,:2] 

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each indexexcept for the final one
rank_4_tensor[:1 , :1 , :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor (2 dimensins)
rank_2_tensor= tf.constant([[10,7],
                           [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
# try to get last element each row
rank_2_tensor[:] 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# try to get last element each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# try to get first element each row
rank_2_tensor[:,0:1] 

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 3]], dtype=int32)>

In [ ]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_3_tensor.ndim

3

In [ ]:
rank_4_tensor = rank_3_tensor[...,tf.newaxis]

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis with -1 means  expand to final aixs
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis expand to 0-axis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis expand to 0-axis
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# Manipulating tensors ( tensor operations
**Basic Operations**
- + ,- ,* , /

In [ ]:
# add values to a tensor using addition operator
tensor =tf.constant([[10,7],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# muliplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# substraction 
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# we can use the tensorflow built in functjion too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In Machine Learning, Matrix multiplication is on of the most common tensor operations.

There are two before any matrix operation
- The inner dimensions must match
- The resulting matrix has the shape of the outter dimensions.

In [ ]:
# matrix multiplication in tens (with dot product)
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matrix multiplication in tens (with dot product)
print(tensor)
tensor @ tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# matrix multiplication in tens (with Element by Element)
print(tensor)
tensor*tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# create a tensor (3,2)
x = tf.constant ([[1,2],
                  [3,4],
                  [5,6]])

In [ ]:
# create tensor (3,2)
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# try to matrix to multiplicaiton
tf.matmul(x,y)

InvalidArgumentError: ignored

In [ ]:
# lets change the shape of y
Y =tf.reshape(y,shape=(2,3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# try to matrix to multiplicaiton
tf.matmul(x,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# try to change the shape of x and multiply with y
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# can do the same with transpose
tf.transpose(x),tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The Dot Product**

Matrix Multiplication is also referred to as the dont product.

You can perform matrix multlipicatkion using

- tf.matmul()
- tf.tensdordot()

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# perform the dot product on X and Y (require X or y to be transposed )
tf.tensordot(tf.transpose(x),y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix mulplication between x and y (trasnposed)
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix mulplication between x and y (reshaped)
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of Y and, reshape Y and Tranposed Y
print('Normal Y: ')
print(y, '\n') # new line \

print('Reshaped Y: ')
print(tf.reshape(y,shape =(2,3)), '\n')

print('Transposed Y: ')
print(tf.transpose(y), '\n')


Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



# Changing the datatypes of a tensor

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
# create a new tensor with default datatype (float32)
B= tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C= tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# change datatype float32 to float16 (reduce precision)
B =tf.cast(B,dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# change datatype float32 to float16 (reduce precision)
D =tf.cast(B,dtype=tf.float16)
D, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

**Aggreting Tensor**

- Aggregating tensors = condesing them from multiple values to a smaller amount of values.

In [ ]:

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
## change datatype float32 to float16 (reduce precision)
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Lets go through the following froms of aggregatins:
- Min
- Max
- Mean
- Sum

In [ ]:
# Create tensor of random number 0 to 50 with size 50
E= tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([75, 17, 83, 72, 45, 76, 34, 59,  7,  1, 72, 81, 67,  6, 15, 97, 43,
       91, 38, 44, 67, 55, 48, 10, 23, 53, 94, 94, 38, 58, 27,  5, 40, 71,
       14,  8, 23, 32,  1, 69, 62, 64, 50, 49, 56, 38, 44, 13, 37, 46])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
Ag = tf.constant([10,20,30])

In [ ]:
# lets try to apply above operation
# Min 
tf.math.reduce_min(Ag)


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# lets try to apply above operation
# Max
tf.math.reduce_max(Ag)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# lets try to apply above operation
# Mean
tf.math.reduce_mean(Ag)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [ ]:
# lets try to apply above operation
# sum
tf.math.reduce_sum(Ag)

<tf.Tensor: shape=(), dtype=int32, numpy=60>

- Find out varinace and standard deviation of tensor E using tensorflow methods.

In [ ]:
# Find the variance , to find out variance we need tensorflow_Probability 
# lets import llibrary

import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=714>

In [ ]:
# find the standard deviation 
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.720448>

### Find the positional maximum and minimum

In [ ]:
# create new tensor for postitional maximum and minimu
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# at which maximum value occured 
# find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# INdex on our largest value position
F[tf.argmax(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# lets check max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# INdex on our smallest value position
F[tf.argmin(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor (removing all single dimensions)


In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Squeezed will reduce the all single diamension elements
G_squeezed =tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
G_squeezed.shape

TensorShape([50])

### One-hot encoding

In [ ]:
some_list =[0,1,2,3]

In [ ]:
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Math Operation
- Square
- Log
- Square Root

In [ ]:
# create tensor with new method
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.math.sqrt(H) # we wll get error here , here we required method here.

InvalidArgumentError: ignored

In [ ]:
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(H) # error happend here.Need to change dtype

InvalidArgumentError: ignored

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

### Tensor and NumPy

- TensorFlow interects beautifully with Numpy arrays


In [ ]:
# create a tensor directly from a NUmPY array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert tensor into numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a Numpy array ( other method)
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The defult types of each are slighlty different
numpy_J =tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])

In [ ]:
# check datatype of each
numpy_J.dtype,tensor_J

(tf.float64,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

**___________________________________________________________**

# ***--------FINISH---------***

### **Exercise**

## **1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().**






In [ ]:
# scaler (rank = 0)
scaler =tf.constant(18)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [ ]:
scaler.ndim

0

In [ ]:
# vector (rank = 1)
vector =tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# matrix (rank = 2)
matrix =tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# tensor (rank = 3)  we can create upto n
tensor = tf.constant([[[1,2,3],[4,5,6]]])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## **2.Find the shape, rank and size of the tensors you created in 1.**

In [ ]:
# get various attribute of our tensor
print('Datatype of every element: ',rank_4_tensor.dtype)
print('Number of dimensions (rank): ',rank_4_tensor.ndim)
print('Shape of tensor: ',rank_4_tensor.shape)
print('Elements along the 0 axis: ',rank_4_tensor.shape[0])
print('Elements along the last axis: ',rank_4_tensor.shape[-1])
print('Number of Elements in tensor: ',tf.size(rank_4_tensor))
print('Number of Elements in tensor: ',tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'int32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 2, 1, 1)
Elements along the 0 axis:  2
Elements along the last axis:  1
Number of Elements in tensor:  tf.Tensor(4, shape=(), dtype=int32)
Number of Elements in tensor:  4


In [ ]:
# scaler
vector.shape[0]

3

In [ ]:
# shape
tf.shape(vector).shape[0]

1

In [ ]:
# ranks
scaler.ndim

0

In [ ]:
#size
tf.size(scaler).numpy()

1

In [ ]:
# get various attribute of our scaler
print('Information about Scaler')
print('Shape of tensor: ',scaler.shape)
print('Number of dimensions (rank): ',scaler.ndim)
print('Number of Elements in tensor: ',tf.size(scaler).numpy())

Information about Scaler
Shape of tensor:  ()
Number of dimensions (rank):  0
Number of Elements in tensor:  1


In [ ]:
# get various attribute of our vector
print('Information about vector')
print('Shape of tensor: ',vector.shape)
print('Number of dimensions (rank): ',vector.ndim)
print('Number of Elements in tensor: ',tf.size(vector).numpy())

Information about vector
Shape of tensor:  (3,)
Number of dimensions (rank):  1
Number of Elements in tensor:  3


In [ ]:
# get various attribute of our matrix
print('Information about matrix')
print('Shape of matrix: ',matrix.shape)
print('Number of dimensions (rank): ',matrix.ndim)
print('Number of Elements in matrix: ',tf.size(matrix).numpy())

Information about matrix
Shape of matrix:  (2, 3)
Number of dimensions (rank):  2
Number of Elements in matrix:  6


In [ ]:
# get various attribute of our tensor
print('Information about tensor')
print('Shape of tensor: ',tensor.shape)
print('Number of dimensions (rank): ',tensor.ndim)
print('Number of Elements in tensor: ',tf.size(tensor).numpy())

Information about tensor
Shape of tensor:  (1, 2, 3)
Number of dimensions (rank):  3
Number of Elements in tensor:  6


### 3.Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [ ]:
# lets create random tensor values between (0 to 1 with shape 5,300)
rand_tensor=tf.constant(np.random.randint(0,1),shape=(5,300))
rand_tensor





<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
# get various attribute of our tensor
print('Information about tensor')
print('Shape of tensor: ',rand_tensor.shape)
print('Number of dimensions (rank): ',rand_tensor.ndim)
print('Number of Elements in tensor: ',tf.size(rand_tensor).numpy())


Information about tensor
Shape of tensor:  (5, 300)
Number of dimensions (rank):  2
Number of Elements in tensor:  1500


### **4.Multiply the two tensors you created in 3 using matrix multiplication.**

In [ ]:
rand_tensor=tf.constant(np.random.randint(0,1),shape=(5,300))
rand_tensor

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
# multipication operation by 2
tf.multiply(2,rand_tensor)

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

## **5.Multiply the two tensors you created in 3 using dot product**

In [ ]:
# lets create random tensor values between (0 to 1 with shape 5,300)
rand_tensor_01=tf.constant(np.random.randint(0,1),shape=(5,300))
rand_tensor_01

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
rand_tensor_02=tf.constant(np.random.randint(0,1),shape=(5,300))
rand_tensor_02

<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

In [ ]:
# lets perform dot matrix multipication
tf.tensordot(rand_tensor_01,tf.transpose(rand_tensor_02),axes=1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

### **6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].**

In [ ]:
# let create tensor with 0 to 1 (shape-224,224,3)
tensor_224=tf.constant(np.random.randint(0,1),shape=(224,224,3),dtype=tf.float32)
tensor_224

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

## **7.Find the min and max values of the tensor you created in 6 along the first axis.**

In [ ]:
# lets go for argmin
tf.argmin(tensor_224)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]

In [ ]:
# lets check for max
tf.argmax(tensor_224)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
tf_tensor_03=tf.constant(np.random.randint(1,100),shape=(1,224,224,3))

In [ ]:
tf_tensor_03

<tf.Tensor: shape=(1, 224, 224, 3), dtype=int32, numpy=
array([[[[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]],

        [[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]],

        [[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]],

        ...,

        [[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]],

        [[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]],

        [[23, 23, 23],
         [23, 23, 23],
         [23, 23, 23],
         ...,
         [23, 23, 23],
         [23, 23, 23],
         [23, 23, 23]]]], dtype

In [ ]:
# lets perform squeeze operations
tf.squeeze(tf_tensor_03)

<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
array([[[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       ...,

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23],
        ...,
        [23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]]], dtype=int32)>

### **9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.**



In [ ]:
tensor_10=tf.constant(np.arange(1,11),shape=(10))
tensor_10

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [ ]:
# lets find the max value and its index
tf.argmax(tensor_10)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

### **10. One-hot encode the tensor you created in 9.**

In [ ]:
element=[1,2,3,4,5,6,7,8,9]

In [ ]:
tf.one_hot(element,depth=9)

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>